version: '2'
services:
  youtrack:
    container_name: youtrack
    image: pojo-youtrack:latest
    build:
      context: .
      dockerfile: Dockerfile-youtrack
      args:
        - "YOUTRACK_VERSION=2017.1.30791"
    ports:
      - "8080:8080"
    volumes:
      - ./youtrack/backups:/youtrack/backups:rw
      - ./youtrack/data:/youtrack/data:rw
      - ./youtrack/logs:/youtrack/logs:rw
      - ./youtrack/temp:/youtrack/temp:rw
    restart: always
    depends_on:
      - teamcity
    links:
      - teamcity

  teamcity:
    container_name: teamcity
    image: pojo-teamcity:latest
    build:
      context: .
      dockerfile: Dockerfile-teamcity
    ports:
      - "8081:8111"
    volumes:
      - ./teamcity/data:/data/teamcity_server/datadir:rw
      - ./teamcity/logs:/opt/teamcity/logs:rw
    restart: always
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
      container_name: postgres
      image: postgres:latest
      ports:
        - "5432:5432"
      restart: always

